name: VolleyM Angular-1.0$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - docs/*
      - dev-env/*
      - archive/*

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      npm install -g @angular/cli
      npm install
      ng build --prod
  displayName: 'npm install and build'
- task: AzureFileCopy@3
  inputs:
    SourcePath: dist/vm-app
    azureSubscription: 'Azure VM Prod'
    Destination: 'AzureBlob'
    storage: 'volleymgmtprod'
    ContainerName: '$web'
