name: VolleyM Angular-1.0$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - docs/*
      - dev-env/*
      - archive/*

pr:
  autoCancel: true
  branches:
    include:
    - master

stages:
  - stage: build
    displayName: "Build"
    jobs:
      - job: build
        displayName: 'Build Angualr App'
        pool:
          vmImage: 'windows-2019'

        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'install -g @angular/cli'
          displayName: 'Install NG CLI'

        - task: Npm@1
          inputs:
            command: 'install'
          displayName: 'npm install'

        - task: PowerShell@2
          inputs:
            targetType: inline
            script: ng build -c=staging
          displayName: 'build'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'dist/vm-app'
            ArtifactName: 'volleyM-angular.app'
            publishLocation: 'Container'

        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: '9b3ded99-cb46-49c1-a300-5a7bd56461a5'
            vstsFeedPackagePublish: 'volleym-angular-app'
            versionOption: 'patch'
            packagePublishDescription: 'volleym-angular-app'

  # - stage: staging
  #   displayName: 'Integration'
  #   jobs:
  #     - job: deploy_staging
  #       pool:
  #         vmImage: 'windows-2019'
  #       displayName: 'Deploy Staging Firebase'
  #       steps:
  #         - task: Down

