name: VolleyM Angular-1.0$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
      - docs/*
      - dev-env/*
      - archive/*

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod --outputPath $(Build.StagingDirectory)
  displayName: 'npm install and build'
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.StagingDirectory)/vm-app'
    ConnectedServiceNameARM: 'Azure VM Prod'
    Destination: 'AzureBlob'
    storage: 'volleymgmtprod'
    ContainerName: '$web'
